services:
  avi-shopper-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_HOST=0.0.0.0
      - VITE_ALLOWED_HOSTS=all,avi.tooxs.ai
      - HOST=0.0.0.0
      - PORT=5173
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: avi-shopper-mvp
    network_mode: "bridge"
